// Code generated by thriftrw-plugin-yarpc
// @generated

// Copyright (c) 2017 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package keyvalueclient

import (
	"context"
	"reflect"
	"go.uber.org/thriftrw/wire"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/internal/examples/thrift-keyvalue/keyvalue/many/services"
	"go.uber.org/yarpc/internal/examples/thrift-keyvalue/keyvalue/many/unions"
	"go.uber.org/yarpc/encoding/thrift"
	"go.uber.org/yarpc"
)

// Interface is a client for the KeyValue service.
type Interface interface {
	DeleteValue(
		ctx context.Context,
		Key *services.Key,
		opts ...yarpc.CallOption,
	) error

	GetManyValues(
		ctx context.Context,
		Range []services.Key,
		opts ...yarpc.CallOption,
	) ([]*unions.ArbitraryValue, error)

	GetValue(
		ctx context.Context,
		Key *services.Key,
		opts ...yarpc.CallOption,
	) (*unions.ArbitraryValue, error)

	SetValue(
		ctx context.Context,
		Key *services.Key,
		Value *unions.ArbitraryValue,
		opts ...yarpc.CallOption,
	) error

	SetValueV2(
		ctx context.Context,
		Key services.Key,
		Value *unions.ArbitraryValue,
		opts ...yarpc.CallOption,
	) error

	Size(
		ctx context.Context,
		opts ...yarpc.CallOption,
	) (int64, error)
}

// New builds a new client for the KeyValue service.
//
// 	client := keyvalueclient.New(dispatcher.ClientConfig("keyvalue"))
func New(c transport.ClientConfig, opts ...thrift.ClientOption) Interface {
	return client{
		c: thrift.New(thrift.Config{
			Service:      "KeyValue",
			ClientConfig: c,
		}, opts...),
	}
}

func init() {
	yarpc.RegisterClientBuilder(
		func(c transport.ClientConfig, f reflect.StructField) Interface {
			return New(c, thrift.ClientBuilderOptions(c, f)...)
		},
	)
}

type client struct {
	c thrift.Client
}

func (c client) DeleteValue(
	ctx context.Context,
	_Key *services.Key,
	opts ...yarpc.CallOption,
) (err error) {

	args := services.KeyValue_DeleteValue_Helper.Args(_Key)

	var body wire.Value
	body, err = c.c.Call(ctx, args, opts...)
	if err != nil {
		return
	}

	var result services.KeyValue_DeleteValue_Result
	if err = result.FromWire(body); err != nil {
		return
	}

	err = services.KeyValue_DeleteValue_Helper.UnwrapResponse(&result)
	return
}

func (c client) GetManyValues(
	ctx context.Context,
	_Range []services.Key,
	opts ...yarpc.CallOption,
) (success []*unions.ArbitraryValue, err error) {

	args := services.KeyValue_GetManyValues_Helper.Args(_Range)

	var body wire.Value
	body, err = c.c.Call(ctx, args, opts...)
	if err != nil {
		return
	}

	var result services.KeyValue_GetManyValues_Result
	if err = result.FromWire(body); err != nil {
		return
	}

	success, err = services.KeyValue_GetManyValues_Helper.UnwrapResponse(&result)
	return
}

func (c client) GetValue(
	ctx context.Context,
	_Key *services.Key,
	opts ...yarpc.CallOption,
) (success *unions.ArbitraryValue, err error) {

	args := services.KeyValue_GetValue_Helper.Args(_Key)

	var body wire.Value
	body, err = c.c.Call(ctx, args, opts...)
	if err != nil {
		return
	}

	var result services.KeyValue_GetValue_Result
	if err = result.FromWire(body); err != nil {
		return
	}

	success, err = services.KeyValue_GetValue_Helper.UnwrapResponse(&result)
	return
}

func (c client) SetValue(
	ctx context.Context,
	_Key *services.Key,
	_Value *unions.ArbitraryValue,
	opts ...yarpc.CallOption,
) (err error) {

	args := services.KeyValue_SetValue_Helper.Args(_Key, _Value)

	var body wire.Value
	body, err = c.c.Call(ctx, args, opts...)
	if err != nil {
		return
	}

	var result services.KeyValue_SetValue_Result
	if err = result.FromWire(body); err != nil {
		return
	}

	err = services.KeyValue_SetValue_Helper.UnwrapResponse(&result)
	return
}

func (c client) SetValueV2(
	ctx context.Context,
	_Key services.Key,
	_Value *unions.ArbitraryValue,
	opts ...yarpc.CallOption,
) (err error) {

	args := services.KeyValue_SetValueV2_Helper.Args(_Key, _Value)

	var body wire.Value
	body, err = c.c.Call(ctx, args, opts...)
	if err != nil {
		return
	}

	var result services.KeyValue_SetValueV2_Result
	if err = result.FromWire(body); err != nil {
		return
	}

	err = services.KeyValue_SetValueV2_Helper.UnwrapResponse(&result)
	return
}

func (c client) Size(
	ctx context.Context,
	opts ...yarpc.CallOption,
) (success int64, err error) {

	args := services.KeyValue_Size_Helper.Args()

	var body wire.Value
	body, err = c.c.Call(ctx, args, opts...)
	if err != nil {
		return
	}

	var result services.KeyValue_Size_Result
	if err = result.FromWire(body); err != nil {
		return
	}

	success, err = services.KeyValue_Size_Helper.UnwrapResponse(&result)
	return
}
